### ISSUE TITLE
Styles don't fully load when refreshing the page https://prod.foo.redhat.com:1337/insights/advisor/rules

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend-starter-app#31]

**Comment by ryelo** [comment]
@Kinlaw I think this is an issue with Chrome and not with the Starter App. 

Try switching to the `fixes/moving-rules-page` and try hitting that url again. In my case, the page styles still load, but the navigation styles do not.

I'm assuming it has something to do with importing the patternfly navigation styles.

**Comment by ryelo** [comment]
[Referencing PR in Insights-Chrome](https://github.com/RedHatInsights/insights-chrome/pull/12)
