### ISSUE TITLE
blank page at localhost:8002

### ISSUE THREAD

**Issue by thomasmckay** [RedHatInsights/insights-frontend-starter-app#35]
Blank page at _localhost:8002_ with no js errors. On _localhost:8081_ just text "Upgrade Required".

```
$ npm --version
5.6.0
$ node --version
v8.11.3
$ npm run start

> insights-frontend-starter-app@1.1.0 start /home/thomasmckay/code/polpette/frontend
> WEBPACK_SERVE=development webpack-serve --config config/dev.webpack.config.js

clean-webpack-plugin: /home/thomasmckay/code/polpette/frontend/config/dist has been removed.
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:8002
ℹ ｢serve｣: Server URI copied to clipboard
ℹ ｢hot｣: webpack: Compiling Done
ℹ ｢wdm｣: Hash: e1aa538c8492721ff4cc
Version: webpack 4.12.2
Time: 13940ms
Built at: 2018-07-23 16:43:16
... output ...

ℹ ｢wdm｣: Compiled successfully.
ℹ ｢hot｣: WebSocket Client Connected
ℹ ｢hot｣: WebSocket Client Connected
ℹ ｢hot｣: WebSocket Client Connected
```

**Comment by thomasmckay** [comment]
I suspect I'm missing something. Do I need the other repos referenced in the README?

**Comment by ryelo** [comment]
@thomasmckay You will need to set up [Insights Proxy](https://github.com/RedHatInsights/insights-proxy) and [Insights Chrome](https://github.com/RedHatInsights/insights-chrome).

The chroming and the chroming API are used to identify which application you are currently in and running it through local host/not through the proxy won't load the `<esi>` tags. You can see the references to the tags in the [`App.js` file](https://github.com/RedHatInsights/insights-frontend-starter-app/blob/master/src/App.js)

**Comment by ryelo** [comment]
@thomasmckay Are you still running into trouble with this?

**Comment by thomasmckay** [comment]
Closing. I'll try again another day.
