### ISSUE TITLE
ESI in production

### ISSUE THREAD

**Issue by bekasovoleg** [RedHatInsights/insights-frontend-starter-app#75]
Could you explain how ESI provides in production?
Development environment uses [insights-proxy](https://github.com/RedHatInsights/insights-proxy) that uses [spandx](https://github.com/redhataccess/spandx) which provides ESI and some nifty routing tools.
How to provide ESI for production setup?

**Comment by karelhala** [comment]
@iphands might be the best person to answer this question. But basically the akamai is responsible for that [1]

[1] https://www.akamai.com/us/en/support/esi.jsp

**Comment by iphands** [comment]
There's not a ton to explain here. We use Akamai for our edge and they provide an ESI implementation.

Other proxies in edge caches have a similar feature. I think internally there was a team that was using f5s to do the same... I also played around with using varnish as an ESI implementation inside the proxy alone time ago

**Comment by bekasovoleg** [comment]
Thx, @iphands! This info was very helpful.

I have one more question about production setup. Could you tell how is adding `x-rh-identity` header implemented in production?

I've found that `spandx` does it in dev setup. What is about prod?

```
    return new Promise (function (resolve, reject) {
        jwt.verifycookies.cs_jwt, env.keycloakPubkey, {}, function jwtVerifyPromise(err, decoded) {
            if (err) { resolve(target); return; } // silently miss on error
            const user = buildUser(decoded);
            const unicodeUser = new Buffer(JSON.stringify(user), "utf8");
            req.headers["x-rh-identity"] = unicodeUser.toString("base64");
            resolve(target);
        });
    });
```

And let me know if there is place for asking such kind of questions

**Comment by Kinlaw** [comment]
We have some custom 3scale/nginx modules at contact internal services and
some cases and just deconstruct + validate the JWT in other cases to
authenticate users. And then we can show up there x rh identity from there

**Comment by bekasovoleg** [comment]
@Kinlaw, how do you deconstruct + validate the JWT in prod?
